# Generated by Django 4.0.5 on 2023-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_remove_contact_phone_contact_adults_contact_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
