# Generated by Django 4.0.5 on 2023-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0006_alter_contact_adults_alter_contact_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tour_rate', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
