# Generated by Django 4.0.5 on 2023-03-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('small_description', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating_out_of_5', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('about_this', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
