# Generated by Django 4.0.5 on 2023-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
